[package]
name = "notedown-parser"
version = "0.1.0"
authors = ["Aster <galaster@foxmail.com>"]
description = "Notedown Text parser and formatter"
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/nyar-lang/notedown-rs"
exclude = ["/tests/*"]
edition = "2018"


[dependencies]
pest = "2"
pest_derive = "2"

[dev-dependencies]
pest_generator = "2.1.1"
quote = "1.0"
