[package]
name = "notedown_parser"
version = "0.3.0"
authors = ["Aster <192607617@qq.com>"]
description = "Notedown Text parser"
repository = "https://github.com/nyar-lang/notedown-rs"
readme = "README.md"
license = "MPL-2.0"
edition = "2018"


[dependencies]
pest = "2.1.2"

[dev-dependencies]
pest_generator = "2.1.1"
quote = "1.0"
