[package]
name = "notedown-parser"
version = "0.0.3"
authors = ["Aster <galaster@foxmail.com>"]
description = "Notedown Text parser and formatter"
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/nyar-lang/notedown-rs"
exclude = ["/tests/*"]
edition = "2018"


[dependencies]
pest = "2"
pest_derive = "2"
colored ={version= "1.8.0",optional=true}

[dev-dependencies]

[features]
default = ["colored"]


[profile.release]
lto = true
opt-level = "s"