[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/notedown-ast",
    "projects/notedown-runtime",
    "projects/text-utils",
]
exclude = [
    "projects/notedown-parser",
]

[profile.release]
lto = true
opt-level = "s"