[workspace]
members = ["projects/*"]
default-members = [
    "projects/notedown-ast",
    "projects/notedown-lsp",
    "projects/notedown-plugin",
    "projects/notedown-pest",
    "projects/notedown-parser2",
]

[profile.release]
lto = true
opt-level = "s"