[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/notedown-ast",
    "projects/notedown-parser",
    "projects/text-utils",
]
exclude = [

]

[profile.release]
lto = true
opt-level = "s"