[workspace]
members = ["projects/*"]
default-members = [
    "projects/notedown-ast",
    "projects/notedown-pest",
    "projects/notedown-parser",
    "projects/notedown-parser2",
    "projects/notedown-yew-preview",
]

[profile.release]
lto = true
opt-level = "s"