[workspace]

members = ["projects/*"]
default-members = [
    "projects/notedown-parser",
    "projects/notedown-ast",
    "projects/notedown-fmt",
    "projects/notedown-zola",
]

[profile.release]
lto = true
opt-level = "s"