[package]
name = "notedown-rs"
version = "0.0.1"
authors = ["Aster <galaster@foxmail.com>"]
description = "Prime lib for Nyar"
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/nyar-lang/nyar-prime"
exclude = ["/tests/*", "/.idea/*"]
edition = "2018"

[lib]
crate-type = ["dylib", "rlib"]
name =  "notedown"
path = "src/lib.rs"

#[[bin]]
#name = "comrak"
#required-features = ["clap"]
#doc = false

[dependencies]
pest = "2"
pest_derive = "2"
colored ={version= "1.8.0",optional=true}

[dev-dependencies]

[features]
default = ["colored"]


[profile.release]
lto = true
opt-level = "s"