[workspace]
members = ["projects/*"]
default-members = [
    "projects/notedown-ast",
    "projects/notedown-parser",
    "projects/notedown-plugin",
]
exclude = [
    "projects/notedown-pest",
    "projects/notedown-parser2",
]

[profile.release]
lto = true
opt-level = "s"