[package]
name = "notedown-rt"
version = "0.3.1"
authors = ["Aster <192607617@qq.com>"]
description = "Notedown Text parser"
repository = "https://github.com/notedge/notedown-rs/tree/master/projects/notedown-runtime"
documentation = "https://docs.rs/notedown-rt"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"


[dependencies]
notedown_ast = { version = "0.16", path = "../notedown-ast" }
async-std = "1.10.0"
self_update = "0.28.0"
chrono = "0.4.19"
globset = "0.4.8"
rsass = { version = "0.23.0", optional = true }
yggdrasil-shared = { version = "0.1.7", optional = true }


[dependencies.notedown-error]
version = "1.0"
path = "../notedown-error"
features = ["globset", "chrono"]

[dev-dependencies]

[features]
default = ["lsp"]
lsp = [
    "yggdrasil-shared",
    "yggdrasil-shared/lsp",
    "notedown-error/yggdrasil-shared",
    "notedown-error/lsp-types"
]
