[package]
name = "notedown-rt"
version = "0.1.0"
authors = ["Aster <192607617@qq.com>"]
description = "Notedown Text parser"
repository = "https://github.com/notedge/notedown-rs"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"


[dependencies]
notedown_ast = {version = "0.14", path = "../notedown-ast", features = ["globset"]}
dashmap = "5.0.0"
globset = "0.4.8"
async-std = "1.10.0"
ropey = "1.3.1"

[dependencies.syntect]
version = "4.6.0"
optional = true
features = ["metadata"]

[dependencies.self_update]
version = "0.28.0"


[dev-dependencies]

[features]
default = ["syntect"]