package notedown: core↯0.1.0;

world host {
    export types;
    export syntax-tree;
    export math;
    export code;
}

interface types {
    record object {
        map: list<tuple<string, value>>,
    }
    variant value {
        %null,
        %bool(bool),
        %integer(s64),
        %decimal(f64),
        %string(string),
        %url(url),
    }
    variant notedown-error {
        syntax(syntax-error),
    }


    resource url {

    }
    record text-range {
        head-offset: u32,
        tail-offset: u32,
    }
    record syntax-error {
        reason: string,
        file: option<url>,
        range: text-range,
    }
}

interface syntax-tree {
    use types.{text-range, url, object, notedown-error};

    record notedown-root {
        blocks: list<root-item>,
        config: object,
        path: option<url>
    }
    variant root-item {
        %placeholder,
        %heading(heading-block),
        %horizontal-rule(horizontal-rule),
        %paragraph(paragraph-block),
        %space-break(breakline-block),
        %code(code-environment),
        %math(math-environment),
        %list(list-environment),
        %table(table-environment),
    }

    // === title block === -----------------------------------------------------------------------------
    /// \title { text }
    record heading-block {
        level: u8,
        title: paragraph-block,
        range: text-range,
    }
    // === line breaks === -----------------------------------------------------------------------------
    /// The line break block
    /// ```note
    /// ===
    /// ````
    record horizontal-rule {
        lines: u32,
        range: text-range,
    }
    record breakline-block {
        lines: u32,
        range: text-range,
    }
    record space-inline {
        space: string,
        range: text-range,
    }
    // === line breaks === -----------------------------------------------------------------------------
    /// The math text written in the paragraph
    ///
    /// ### Example
    /// ````note
    /// ```code(key: args)
    /// ```
    /// ````
    record code-environment {
        action: command-action,
        lines: string,
        range: text-range,
    }
    record command-environment {
        action: command-action,
        range: text-range,
    }
    variant command-action {
        /// anonymous highlighting
        anonymous,
        highlight(code-highlight),
    }
    /// The math text written in the paragraph
    ///
    /// ### Example
    /// ````note
    /// ```language
    /// highlight
    /// ```
    /// ````
    record code-highlight {
        language: string,
        range: text-range,
    }
    // === line breaks === -----------------------------------------------------------------------------
    /// The math text written in the paragraph
    ///
    /// ### Example
    /// ```note
    /// The naunce of the universe is $6.022\times 10^{23}$
    /// ```
    record math-environment {
        display: math-display,
        content: math-content,
        range: text-range,
    }
    variant math-display {
        inline,
        block
    }
    variant math-content {
        /// MathML element
        mathml(string),
        /// TeX ompatible formulas, including `mathjax` and `katex`
        tex(string),
        asciimath(string),
    }
    // === line breaks === -----------------------------------------------------------------------------
    record list-environment {
        items: list<list-item>,
        range: text-range,
    }
    record list-item {
        level: u32,
        // content: list<paragraph-block>,
        checked: option<bool>,
        range: text-range,
    }
    // === line breaks === -----------------------------------------------------------------------------
    record table-environment {
        rows: list<table-row>,
        range: text-range,
    }
    record table-row {
        cells: list<table-cell>,
        range: text-range,
    }
    record table-cell {
        // content: paragraph-block,
        range: text-range,
    }
    // === paragraph environment === -----------------------------------------------------------------------------
    record paragraph-block {
        terms: list<paragraph-item>,
        range: text-range,
    }
    variant paragraph-item {
        %placeholder,
        %text(normal-text),
        %style(styled-text),
        %math(math-environment),
        %code(code-environment),
        %link(link-reference),
        %image(image-reference),
    }
    record normal-text {
        text: string,
        range: text-range,
    }
    record styled-text {
        %type: style-type,
        // items: list<paragraph-item>,
        range: text-range,
    }
    flags style-type {
        bold,
        italic,
        underline,
        strikethrough,
    }
    /// `\image(url, text)`
    record image-reference {
        url: option<url>,
        alternative: string,
        range: text-range,
    }
    /// `\link(url, text)`
    record link-reference {
        url: option<url>,
        title: string,
        range: text-range,
    }
}

interface math {
    resource math-render {

    }
}

interface code {
    resource code-render {

    }
}
