[package]
name = "notedown_ast"
version = "0.3.0"
authors = ["Aster <192607617@qq.com>"]
description = "..."
repository = "https://github.com/nyar-lang/Notedown-rs"
readme = "README.md"
license = "MPL-2.0"
edition = "2018"
exclude = ["/tests/*"]

[dependencies]
pest = "2.1.2"
textwrap = "0.11"
chrono = "0.4.10"

notedown_parser = {path = "../notedown-parser",version = "0.4.0"}

[dev-dependencies]

[features]
