[package]
name = "notedown_ast"
publish = false
version = "0.7.0"
authors = ["Aster <192607617@qq.com>"]
description = "notedown ast and converter"
repository = "https://github.com/nyar-lang/Notedown-rs"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2018"

[dependencies]
text-utils = "0.2"
# notedown = {version = "0.3", optional = true}
# orgize = {version = "0.8", optional = true}
url = "2.1"

[dev-dependencies]

[features]
default = []
# convert = ["notedown", "orgize"]
