[package]
name = "notedown_ast"
version = "0.12.0"
authors = ["Aster <192607617@qq.com>"]
description = "notedown ast and converter"
repository = "https://github.com/notedge/notedown-rs"
readme = "../../readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
text-utils = "0.3.0"
lsp-types = { version = "0.91.1", optional = true, features = ["proposed"] }
num = "0.4"
itertools = "0.10.1"
indexmap = "1.7"

[dev-dependencies]

[features]
default = ["lsp"]
web = []
lsp = ["lsp-types"]
