[package]
name = "notedown_ast"
version = "0.0.1"
authors = ["192607617@qq.com"]
edition = "2018"
description = "..."
repository = "https://github.com/nyar-lang/NyarNative"
license = "MPL-2.0"

[dependencies]
pest = "2.1.2"
textwrap = "0.11"
notedown_parser = {path = "../notedown-parser",version = "0.2.0"}

[dev-dependencies]

[features]

[profile.release]
lto = true
opt-level = "s"