[package]
name = "notedown_ast"
version = "0.8.1"
authors = ["Aster <192607617@qq.com>"]
description = "notedown ast and converter"
repository = "https://github.com/nyar-lang/Notedown-rs"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2018"

[dependencies]
text-utils = "0.3"

[dev-dependencies]

[features]
default = []
