[package]
name = "notedown_ast"
version = "0.14.1"
authors = ["Aster <192607617@qq.com>"]
description = "notedown ast and converter"
repository = "https://github.com/notedge/notedown-rs"
readme = "../../readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
text-utils = "0.3.0"
yggdrasil-shared = "0.1.5"
num = "0.4.0"
itertools = "0.10.3"
indexmap = "1.7.0"
#notedown-image = { version = "0.1", path = "../notedown-image", optional = true }
dashmap = "5.0.0"
pest = { version = "2.1.3", optional = true }


[dev-dependencies]

[features]
default = []
storage = []


