[package]
name = "notedown_ast"
version = "0.8.3"
authors = ["Aster <192607617@qq.com>"]
description = "notedown ast and converter"
repository = "https://github.com/nyar-lang/Notedown-rs"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2018"

[dependencies]
text-utils = "0.3"
# lsp-types = { version = "0.86", features = ["proposed"] }
yew = { version =  "0.17", optional = true }
yew-katex = { version =  "0.2", optional = true }

[dev-dependencies]

[features]
default = ["render"]
render = ["yew", "yew-katex"]